/* ── BLOQUE 4 · TÉCNICAS DE DISEÑO · aquí se gana o se pierde el examen ─── */
{ n:21, bloque:4, titulo:'Contar particiones', tipo:'numero',
  enunciado:'Un campo «cantidad de boletos» acepta de <b>1 a 10</b>. Cualquier otro valor entero se rechaza.\n\n¿Cuántas particiones de equivalencia hay, contando válidas e inválidas?',
  respuesta:3,
  pistas:['Una partición es un grupo de valores que el sistema trata igual.',
          'Hay una partición válida. ¿Cuántas maneras hay de estar fuera?',
          'Se puede estar por debajo o por encima, y son dos grupos distintos.'],
  pasos:['Válida: de 1 a 10. Es <b>1</b> partición.',
         'Inválida por abajo: menor que 1. Es <b>1</b>.',
         'Inválida por arriba: mayor que 10. Es <b>1</b>.',
         'Total: <b>3</b> particiones.',
         'El error clásico es contar sólo la válida, o inventar una cuarta («vacío») que la especificación no menciona.'],
  porque:'Contar particiones es el paso 1 de media docena de preguntas del examen. Si lo cuentas mal, todo lo que sigue sale mal.' },

{ n:22, bloque:4, titulo:'Límites de dos valores', tipo:'multi',
  enunciado:'Para el mismo campo de <b>1 a 10</b>, marca los valores que hay que probar con el método de <b>dos valores</b>.',
  opciones:['0','1','2','9','10','11'],
  correctas:[0,1,4,5],
  pistas:['Dos valores por límite: el límite mismo y su vecino de fuera.',
          'Hay dos límites: el de abajo y el de arriba.',
          'Los vecinos de dentro (2 y 9) son del método de TRES valores.'],
  pasos:['Límite inferior: <b>1</b> (el límite) y <b>0</b> (su vecino de fuera).',
         'Límite superior: <b>10</b> (el límite) y <b>11</b> (su vecino de fuera).',
         'Total con el método de dos valores: 0, 1, 10, 11.',
         'Si además metieras 2 y 9 estarías usando el método de <b>tres valores</b>.'],
  porque:'La confusión entre dos y tres valores cuesta puntos. Dos valores = 4 números por rango; tres valores = 6.' },

{ n:23, bloque:4, titulo:'Límites de tres valores', tipo:'numero',
  enunciado:'Un campo de edad válido acepta de <b>18 a 65</b>.\n\nCon el método de <b>tres valores</b>, ¿cuántos valores distintos hay que probar en total, contando los dos límites de esa partición?',
  respuesta:6,
  pistas:['Tres valores por límite: el límite y sus dos vecinos, uno de cada lado.',
          'La partición válida tiene dos límites: el 18 y el 65.',
          'Comprueba que ninguno se repita entre los dos grupos.'],
  pasos:['Límite inferior <b>18</b>: se prueban <b>17, 18, 19</b>.',
         'Límite superior <b>65</b>: se prueban <b>64, 65, 66</b>.',
         'Ninguno se repite: son <b>6</b> valores distintos.',
         'Con el método de <b>dos valores</b> serían sólo 4: 17, 18, 65 y 66.'],
  porque:'Dos valores da 4 números por partición; tres valores da 6. Confundirlos es el error más común de esta técnica.' },

{ n:24, bloque:4, titulo:'Casos mínimos por particiones', tipo:'numero',
  enunciado:'Un sistema de envíos cobra así, según el peso:\n\n• 0 a 5 kg → tarifa fija\n• 5.01 a 20 kg → tarifa por kilo\n• más de 20 kg → no se acepta\n\nSegún esa especificación, ¿cuántos casos hacen falta <b>como mínimo</b> para el 100 % de cobertura de particiones?',
  respuesta:3,
  pistas:['Cobertura de particiones = al menos un caso por partición.',
          'Cuenta cuántas particiones define la especificación, ni una más.',
          'No inventes particiones que el enunciado no menciona.'],
  pasos:['La especificación define tres particiones: 0–5, 5.01–20 y más de 20.',
         'Un caso por partición: <b>3 casos</b>.',
         'Si también consideraras el peso negativo serían 4, pero la especificación no lo menciona.',
         'Regla de oro del examen: se cuenta lo que la especificación dice, no lo que uno imagina.'],
  porque:'La tentación de añadir particiones «obvias» es el error más caro de esta técnica. La especificación manda.' },

{ n:25, bloque:4, titulo:'Columnas de una tabla de decisión', tipo:'numero',
  enunciado:'Una promoción depende de <b>cinco</b> condiciones booleanas: es socio, monto mayor a 1000, primera compra del mes, tiene cupón, y compra en fin de semana.\n\nSin colapsar, ¿cuántas columnas tiene la tabla de decisión?',
  respuesta:32,
  pistas:['Cada condición booleana tiene dos valores posibles.',
          'La fórmula es 2 elevado a n.',
          '2⁵.'],
  pasos:['Cada condición booleana admite dos valores: verdadero o falso.',
         'Con n condiciones, las combinaciones son <b>2ⁿ</b>.',
         '2⁵ = <b>32 columnas</b>.',
         'Por eso se colapsan: con seis condiciones ya serían 64, y con ocho, 256.'],
  porque:'La fórmula 2ⁿ es de las pocas que hay que saber de memoria. Con tres condiciones son 8, con cuatro 16, con cinco 32.' },

{ n:26, bloque:4, titulo:'Leer una tabla colapsada', tipo:'numero',
  enunciado:'Una tabla de decisión colapsada de un cajero:\n\n<table><tr><th>Condición</th><th>R1</th><th>R2</th><th>R3</th><th>R4</th></tr><tr><td>Tarjeta válida</td><td>N</td><td>S</td><td>S</td><td>S</td></tr><tr><td>PIN correcto</td><td>–</td><td>N</td><td>S</td><td>S</td></tr><tr><td>Saldo suficiente</td><td>–</td><td>–</td><td>N</td><td>S</td></tr><tr><td><b>Entrega efectivo</b></td><td>No</td><td>No</td><td>No</td><td>Sí</td></tr></table>\n\n¿Cuántos <b>casos de prueba</b> hacen falta como mínimo para cubrir todas las reglas de esta tabla?',
  respuesta:4,
  pistas:['Cada columna de la tabla es una regla.',
          'Cada regla necesita al menos un caso de prueba.',
          'Los guiones no añaden casos: significan «da igual».'],
  pasos:['Cada <b>columna</b> es una regla, y cada regla necesita al menos <b>un caso</b>.',
         'Hay 4 columnas → <b>4 casos</b>.',
         'El guion significa «no aplica, no afecta al resultado en esta regla». No suma casos: es justo lo que permite colapsar.',
         'Sin colapsar serían 2³ = 8 columnas, y la tabla dice lo mismo con la mitad.'],
  porque:'La cobertura de tabla de decisión se mide en columnas ejecutadas, no en condiciones.' },

{ n:27, bloque:4, titulo:'Contar transiciones válidas', tipo:'numero',
  enunciado:'Una puerta automática tiene tres estados y estas transiciones válidas:\n\n• Cerrada + «detecta persona» → Abriendo\n• Abriendo + «termina apertura» → Abierta\n• Abierta + «pasan 5 s sin nadie» → Cerrando\n• Cerrando + «termina cierre» → Cerrada\n• Cerrando + «detecta persona» → Abriendo\n\n¿Cuántas transiciones válidas hay que ejercer para el <b>100 % de cobertura 0-switch</b>?',
  respuesta:5,
  pistas:['0-switch quiere decir: cada transición válida, al menos una vez.',
          'No cuentes estados: cuenta flechas.',
          'Las flechas están listadas una por renglón.'],
  pasos:['La cobertura <b>0-switch</b> exige ejercer cada transición válida al menos una vez.',
         'El enunciado lista <b>5</b> transiciones.',
         'Respuesta: 5.',
         'Ojo con la trampa habitual: el número de <b>estados</b> (aquí serían 4 contando Abriendo y Cerrando) no es la respuesta.'],
  porque:'La confusión estados/transiciones es la trampa número uno de esta técnica.' },

{ n:28, bloque:4, titulo:'1-switch: pares consecutivos', tipo:'numero',
  enunciado:'Una máquina de estados con tres transiciones:\n\n• T1 · A + x → B\n• T2 · B + y → C\n• T3 · B + z → A\n\nDesde C no sale ninguna transición.\n\nPara la cobertura <b>1-switch</b> hay que ejercer cada <b>par de transiciones consecutivas</b> posible. ¿Cuántos pares distintos hay?',
  respuesta:3,
  pistas:['Un par (Ti, Tj) es válido si el estado donde TERMINA Ti es el estado donde EMPIEZA Tj.',
          'Prueba las nueve combinaciones posibles y descarta las que no encajan.',
          'No olvides los pares que vuelven sobre una transición ya usada: T3 termina en A, y desde A sale algo.'],
  pasos:['Regla: (Ti, Tj) vale si el estado final de Ti es el inicial de Tj.',
         '<b>T1</b> termina en B. Desde B salen T2 y T3 → pares <b>(T1,T2)</b> y <b>(T1,T3)</b>.',
         '<b>T2</b> termina en C. Desde C no sale nada → ningún par.',
         '<b>T3</b> termina en A. Desde A sale T1 → par <b>(T3,T1)</b>.',
         'Total: <b>3</b> pares.'],
  porque:'1-switch encuentra defectos de secuencia: el sistema hace bien cada paso suelto y se rompe cuando dos van seguidos. La trampa es olvidar los pares que regresan.' },

{ n:29, bloque:4, titulo:'Cobertura de sentencias', tipo:'numero',
  enunciado:'Con el único caso <b>edad = 30</b>, ¿qué porcentaje de <b>cobertura de sentencias</b> obtienes? Cuenta como sentencias ejecutables las líneas 1, 2, 3, 5 y 7. Escribe sólo el número.',
  codigo:['leer edad','si edad >= 18 entonces','· acceso = "permitido"','si no','· acceso = "denegado"','fin si','imprimir acceso'],
  respuesta:80, unidad:'%',
  pistas:['Recorre el código con edad = 30 y anota qué líneas se ejecutan.',
          'La línea 5 sólo se ejecuta si la condición es falsa.',
          'Divide las líneas ejecutadas entre las 5 ejecutables.'],
  pasos:['Con edad = 30 se ejecutan las líneas <b>1, 2, 3 y 7</b>.',
         'La línea <b>5</b> no se ejecuta: es la rama del «si no».',
         '4 de 5 sentencias = <b>80 %</b>.',
         'Las líneas 4 y 6 («si no», «fin si») no son sentencias ejecutables: son marcas de estructura.'],
  porque:'Contar bien qué es una sentencia ejecutable decide el resultado. Las palabras de cierre no cuentan.' },

{ n:30, bloque:4, titulo:'Cobertura de ramas', tipo:'numero',
  enunciado:'Con ese <b>mismo</b> caso único (edad = 30) y ese mismo código, ¿qué porcentaje de <b>cobertura de ramas</b> obtienes?',
  codigo:['leer edad','si edad >= 18 entonces','· acceso = "permitido"','si no','· acceso = "denegado"','fin si','imprimir acceso'],
  respuesta:50, unidad:'%',
  pistas:['Cuenta salidas de decisión, no líneas.',
          'Hay una sola decisión, y toda decisión tiene dos salidas.',
          '¿Cuántas de esas dos recorriste?'],
  pasos:['Hay <b>una</b> decisión (línea 2) y por tanto <b>dos</b> ramas: verdadera y falsa.',
         'Con edad = 30 sólo recorriste la verdadera.',
         '1 de 2 = <b>50 %</b>.',
         'Para llegar al 100 % hace falta un segundo caso, por ejemplo edad = 15.'],
  porque:'Este par de niveles (29 y 30) es la demostración de que ramas es más fuerte que sentencias: 80 % de sentencias con 50 % de ramas.' },

{ n:31, bloque:4, titulo:'Casos mínimos para 100 % de ramas', tipo:'numero',
  enunciado:'¿Cuántos casos hacen falta <b>como mínimo</b> para el 100 % de cobertura de ramas de este código?',
  codigo:['leer A, B','si A > 0 entonces','· si B > 0 entonces','· · imprimir "ambos"','· fin si','fin si','imprimir "fin"'],
  respuesta:3,
  pistas:['Hay dos decisiones, así que hay cuatro salidas que cubrir.',
          'Para llegar a la decisión interna, la externa tiene que ser verdadera.',
          '¿Puedes cubrir la salida falsa de la interna con A ≤ 0? Piénsalo bien.'],
  pasos:['Decisiones: <b>A &gt; 0</b> y <b>B &gt; 0</b>. Cuatro salidas en total.',
         'Caso 1 — A = 5, B = 5: externa <b>verdadera</b>, interna <b>verdadera</b>.',
         'Caso 2 — A = 5, B = −1: externa verdadera, interna <b>falsa</b>.',
         'Caso 3 — A = −1: externa <b>falsa</b>. La interna ni se evalúa.',
         'Con dos casos siempre queda una salida sin recorrer, porque para llegar a la interna hace falta que la externa sea verdadera. Mínimo: <b>3</b>.'],
  porque:'El anidamiento es lo que hace que la respuesta no sea 2. Es la variante que más se falla.' },

{ n:32, bloque:4, titulo:'Depurar: el límite corrido', tipo:'linea',
  enunciado:'La especificación dice: «se aplica descuento a partir de 1000 pesos <b>inclusive</b>». Una prueba con monto = 1000 falla: no aplica descuento.\n\n¿En qué <b>número de línea</b> está el defecto?',
  codigo:['leer monto','descuento = 0','si monto > 1000 entonces','· descuento = monto * 0.10','fin si','total = monto - descuento','imprimir total'],
  respuesta:3,
  pistas:['El caso que falla es exactamente el valor del límite.',
          'Busca la línea donde se compara el monto con 1000.',
          '¿El operador incluye el 1000 o lo deja fuera?'],
  pasos:['Con monto = 1000, la línea 3 evalúa <b>1000 &gt; 1000</b>, que es <b>falso</b>.',
         'La especificación dice «a partir de 1000 <b>inclusive</b>», así que el 1000 debería entrar.',
         'El operador correcto es <b>&gt;=</b>. El defecto está en la <b>línea 3</b>.',
         'Éste es el defecto de límite por excelencia, y es exactamente lo que caza el análisis de valores límite.'],
  porque:'El defecto de «uno de más o uno de menos» vive en el borde. Por eso la técnica de valores límite existe.' },

{ n:33, bloque:4, titulo:'Depurar: la rama que nunca corre', tipo:'linea',
  enunciado:'La especificación: menores de 18 pagan tarifa infantil; de 18 a 64, tarifa normal; 65 o más, tarifa de adulto mayor. Con edad = 70 el sistema cobra <b>tarifa normal</b>.\n\n¿En qué línea está el defecto?',
  codigo:['leer edad','si edad < 18 entonces','· tarifa = "infantil"','si no si edad >= 18 entonces','· tarifa = "normal"','si no si edad >= 65 entonces','· tarifa = "adulto mayor"','fin si','imprimir tarifa'],
  respuesta:4,
  pistas:['Recorre el código con edad = 70 y mira en qué rama se detiene.',
          'Una cadena de «si no si» evalúa en orden y se detiene en la primera que se cumple.',
          '¿Puede llegar el flujo alguna vez a la línea 6?'],
  pasos:['Con edad = 70: la línea 2 (70 &lt; 18) es falsa.',
         'La línea 4 (70 &gt;= 18) es <b>verdadera</b>, así que se asigna «normal» y la cadena termina ahí.',
         'La línea 6 es <b>inalcanzable</b> para cualquier edad: todo lo que llega a ella ya se quedó en la línea 4.',
         'El defecto está en la <b>línea 4</b>: la condición debería ser <b>edad &gt;= 18 y edad &lt; 65</b>, o bien invertir el orden poniendo el 65 primero.',
         'Se marca la línea 4 y no la 6 porque la 6 está bien escrita: lo que está mal es la condición que le roba el paso.'],
  porque:'Un analizador estático marcaría la línea 6 como código inalcanzable. Ése es justo el tipo de hallazgo que la herramienta sí ve.' },

{ n:34, bloque:4, titulo:'Depurar: el bucle que no termina', tipo:'linea',
  enunciado:'Esta función debe sumar los primeros N enteros. Con N = 3 el programa se queda colgado.\n\n¿En qué línea está el defecto?',
  codigo:['leer N','suma = 0','i = 1','mientras i <= N hacer','· suma = suma + i','· imprimir suma','fin mientras','imprimir "listo"'],
  respuesta:6,
  pistas:['Un bucle necesita que algo cambie para poder terminar.',
          '¿Qué variable controla la condición de la línea 4?',
          'Busca dónde debería incrementarse esa variable… y no se incrementa.'],
  pasos:['La condición del bucle es <b>i &lt;= N</b> (línea 4).',
         'Dentro del bucle, <b>i</b> nunca cambia: se suma a <b>suma</b> pero no se incrementa.',
         'La línea 6 debería ser <b>i = i + 1</b> y en su lugar imprime.',
         'El defecto está en la <b>línea 6</b>: falta el incremento del contador.',
         'Con i fijo en 1 y N = 3, la condición 1 &lt;= 3 es verdadera para siempre.'],
  porque:'Es el defecto de bucle infinito clásico. Ninguna cobertura de sentencias lo detecta: la línea se ejecuta, y muchas veces.' },

{ n:35, bloque:4, titulo:'Depurar: la condición combinada', tipo:'linea',
  enunciado:'La regla de negocio: «se aplica la promoción sólo si el cliente es socio <b>y además</b> el monto supera 1000». Con un cliente que <b>no</b> es socio y compra por 5000, el sistema aplica la promoción.\n\n¿En qué línea está el defecto?',
  codigo:['leer socio, monto','promo = "no"','si socio = verdadero o monto > 1000 entonces','· promo = "si"','fin si','descuento = calcular(promo, monto)','imprimir descuento'],
  respuesta:3,
  pistas:['Compara la regla de negocio con lo que dice el código, palabra por palabra.',
          'La regla dice «y además». El código dice otra cosa.',
          'Con un solo operador cambiado, la regla se vuelve mucho más generosa.'],
  pasos:['La regla exige <b>las dos</b> condiciones: socio <b>Y</b> monto &gt; 1000.',
         'La línea 3 usa <b>o</b> en vez de <b>y</b>: basta con que se cumpla una.',
         'Por eso el no socio con 5000 pesos entra: la segunda condición es verdadera.',
         'El defecto está en la <b>línea 3</b>.',
         'Una <b>tabla de decisión</b> con las dos condiciones habría destapado esto en la primera fila: la combinación (no socio, monto alto) tiene resultado distinto en la especificación y en el código.'],
  porque:'Los defectos de operador lógico se cazan combinando condiciones, no probando una a la vez. Para eso existe la tabla de decisión.' },

{ n:36, bloque:4, titulo:'Depurar: el índice fuera de rango', tipo:'linea',
  enunciado:'Esta rutina recorre una lista de 5 elementos, con posiciones del <b>1 al 5</b>. Al ejecutarla revienta con «posición inválida».\n\n¿En qué línea está el defecto?',
  codigo:['leer lista','total = 5','i = 1','mientras i <= total + 1 hacer','· imprimir lista[i]','· i = i + 1','fin mientras','imprimir "fin"'],
  respuesta:4,
  pistas:['¿Hasta qué valor llega i antes de salir del bucle?',
          'Las posiciones válidas van de 1 a 5.',
          'Sustituye total por 5 en la condición y calcula el último valor de i que entra.'],
  pasos:['Con total = 5, la condición es <b>i &lt;= 6</b>.',
         'Así que i llega a valer 6, y la línea 5 pide <b>lista[6]</b>, que no existe.',
         'La condición correcta es <b>i &lt;= total</b>. El defecto está en la <b>línea 4</b>.',
         'Se marca la 4 y no la 5 porque la línea 5 está bien: lo que está mal es cuántas veces se le deja entrar.'],
  porque:'Es otro defecto de límite, esta vez en un bucle. Con probar sólo el elemento del medio nunca aparece.' },

{ n:37, bloque:4, titulo:'Qué técnica escoger', tipo:'opcion',
  enunciado:'Un sistema de reservas se comporta distinto según si la reserva está <b>pendiente</b>, <b>confirmada</b>, <b>en curso</b> o <b>cancelada</b>, y sólo permite ciertos movimientos entre esos situaciones. Sospechas que hay huecos en los movimientos permitidos.\n\n¿Qué técnica modela mejor este problema?',
  opciones:['Análisis de valores límite','Tabla de decisión','Prueba de transición de estados','Cobertura de sentencias'],
  correcta:2,
  pistas:['La palabra clave del enunciado se repite cuatro veces: son situaciones en las que puede estar el sistema.',
          'Cuando el comportamiento depende de en qué situación está y qué evento llega, hay una técnica exacta.',
          'La tabla de decisión sirve cuando el resultado depende de condiciones combinadas, no de una historia previa.'],
  pasos:['Cuatro situaciones + movimientos permitidos entre ellas = <b>estados y transiciones</b>.',
         'La técnica es <b>prueba de transición de estados</b>: se dibuja el diagrama y se cubren las transiciones.',
         'La <b>tabla de decisión</b> serviría si el resultado dependiera de varias condiciones combinadas en un mismo momento, sin memoria de lo anterior.',
         'Los <b>valores límite</b> sirven para rangos numéricos.',
         'La <b>cobertura de sentencias</b> es caja blanca y mide, no diseña.'],
  porque:'Escoger la técnica es media pregunta del examen. La señal de estados es «depende de en qué situación está».' },

{ n:38, bloque:4, titulo:'Colaborativo: las tres C y ATDD', tipo:'multi',
  enunciado:'Marca las afirmaciones <b>correctas</b> sobre el enfoque colaborativo.',
  opciones:['Las tres C son Card, Conversation y Confirmation.',
            'En ATDD los casos de prueba se derivan de los criterios de aceptación antes de implementar.',
            'Los criterios de aceptación los debería escribir sólo la persona de negocio.',
            'El formato Dado / Cuando / Entonces corresponde a criterios orientados a escenarios.',
            'La I de INVEST significa «Implementable».'],
  correctas:[0,1,3],
  pistas:['Dos de las cinco son falsas.',
          'Si los criterios los escribe una sola parte, vuelve el problema que el enfoque colaborativo quiere evitar.',
          'INVEST: Independiente, Negociable, Valiosa, Estimable, Small, Testeable.'],
  pasos:['Las tres C: <b>Card</b> (la tarjeta), <b>Conversation</b> (la conversación) y <b>Confirmation</b> (los criterios). Correcta.',
         'ATDD deriva los casos de los criterios <b>antes</b> de escribir código. Correcta.',
         'Los criterios salen de la conversación entre negocio, desarrollo y pruebas. La 3 es <b>falsa</b>.',
         'Dado / Cuando / Entonces describe un escenario concreto. Correcta.',
         'La I de INVEST es <b>Independiente</b>, no «Implementable». La 5 es falsa.'],
  porque:'INVEST y las tres C se preguntan casi literalmente. Vale la pena aprenderse las seis palabras de INVEST.' },
