/* ── BLOQUE 5 · GESTIÓN ─────────────────────────────────────────────────── */
{ n:39, bloque:5, titulo:'Entrada o salida', tipo:'multi',
  enunciado:'Marca los que son <b>criterios de salida</b> (no de entrada).',
  opciones:['El entorno de prueba está disponible y configurado.',
            'Se ejecutó el 100 % de la cobertura planificada.',
            'La base de prueba está revisada y aprobada.',
            'No quedan defectos abiertos de severidad alta.',
            'Los datos de prueba están cargados.',
            'El informe de finalización está firmado.'],
  correctas:[1,3,5],
  pistas:['Entrada = lo que hace falta para EMPEZAR. Salida = lo que hace falta para DAR POR TERMINADO.',
          'Todo lo que habla de preparación es entrada.',
          'Todo lo que habla de resultados conseguidos es salida.'],
  pasos:['Entrada: entorno, base de prueba aprobada, datos cargados. Son requisitos previos.',
         'Salida: cobertura ejecutada, defectos abiertos bajo el umbral acordado, informe de finalización.',
         'A los criterios de salida también se les llama <b>definition of done</b> en entornos ágiles.'],
  porque:'La pregunta se contesta con una sola idea: ¿esto se necesita antes o se consigue después?' },

{ n:40, bloque:5, titulo:'Estimación de tres puntos', tipo:'numero',
  enunciado:'El equipo estima el esfuerzo de probar un módulo:\n\n• optimista: 8 días\n• más probable: 12 días\n• pesimista: 22 días\n\n¿Cuál es la estimación de tres puntos, en días? Escribe sólo el número.',
  respuesta:13,
  pistas:['La fórmula pondera el valor más probable cuatro veces.',
          '(O + 4M + P) ÷ 6.',
          'Cuidado: el promedio simple daría 14, y no es la respuesta.'],
  pasos:['Fórmula: <b>(optimista + 4 × probable + pesimista) ÷ 6</b>.',
         '(8 + 4 × 12 + 22) ÷ 6',
         '= (8 + 48 + 22) ÷ 6 = 78 ÷ 6 = <b>13 días</b>.',
         'El promedio simple sería (8 + 12 + 22) ÷ 3 = 14. Es la trampa habitual.'],
  porque:'Es la única fórmula de gestión que hay que saber de memoria, y cae casi siempre con números distintos.' },

{ n:41, bloque:5, titulo:'Ordenar por riesgo', tipo:'opcion',
  enunciado:'Cuatro funciones, con su probabilidad de fallo y su impacto (ambos de 1 a 5):\n\n• Cobro con tarjeta → probabilidad 2, impacto 5\n• Buscador de productos → probabilidad 4, impacto 2\n• Cambio de foto de perfil → probabilidad 3, impacto 1\n• Cálculo de impuestos → probabilidad 3, impacto 5\n\n¿Cuál se prueba primero en un enfoque basado en riesgo?',
  opciones:['Cobro con tarjeta','Buscador de productos','Cambio de foto de perfil','Cálculo de impuestos'],
  correcta:3,
  pistas:['El nivel de riesgo es probabilidad por impacto.',
          'Calcula los cuatro productos antes de decidir.',
          'El impacto alto solo no basta si la probabilidad es baja.'],
  pasos:['Cobro con tarjeta: 2 × 5 = <b>10</b>.',
         'Buscador: 4 × 2 = <b>8</b>.',
         'Foto de perfil: 3 × 1 = <b>3</b>.',
         'Cálculo de impuestos: 3 × 5 = <b>15</b>.',
         'El mayor es el cálculo de impuestos. Va primero.'],
  porque:'Riesgo = probabilidad × impacto. Es lo que ordena el trabajo cuando no alcanza el tiempo para probar todo, que es siempre.' },

{ n:42, bloque:5, titulo:'Severidad no es prioridad', tipo:'opcion',
  enunciado:'La portada del sitio, que ven cien mil personas al día, tiene el nombre de la empresa mal escrito. Todo lo demás funciona perfecto.\n\n¿Cómo se clasifica el defecto?',
  opciones:['Severidad alta y prioridad alta','Severidad baja y prioridad posiblemente alta',
            'Severidad alta y prioridad baja','No es un defecto, es una mejora'],
  correcta:1,
  pistas:['Severidad mide el daño técnico que causa el fallo. ¿Se rompió alguna función?',
          'Prioridad mide la urgencia de corregirlo, y la decide el negocio.',
          'Las dos no tienen por qué coincidir.'],
  pasos:['El sistema funciona: no hay pérdida de función ni de datos. La <b>severidad es baja</b>.',
         'Lo ven cien mil personas y afecta la imagen de la empresa. El negocio va a querer que se corrija ya: la <b>prioridad es alta</b>.',
         'Es el ejemplo canónico de severidad baja con prioridad alta.',
         'El caso inverso también existe: un fallo grave en una función que nadie usa hasta dentro de seis meses.'],
  porque:'Severidad la evalúa quien prueba; prioridad la decide el negocio. Que no coincidan es normal, no un error.' },

{ n:43, bloque:5, titulo:'Qué le falta al reporte', tipo:'multi',
  enunciado:'Un reporte de defecto dice sólo esto:\n\n<i>«El sistema truena al guardar. Ya le dije a Miguel que lo arregle porque él escribió esa parte. Adjunto captura.»</i>\n\nMarca <b>todo lo que le falta o le sobra</b> según el temario.',
  opciones:['Faltan los pasos para reproducirlo.',
            'Falta el resultado esperado y el resultado real.',
            'Falta el entorno donde ocurrió (versión, navegador, datos).',
            'Sobra señalar a la persona que escribió el código.',
            'Falta la severidad y la prioridad.',
            'Sobra la captura de pantalla.'],
  correctas:[0,1,2,3,4],
  pistas:['Un reporte tiene que permitir dos cosas: reproducir y decidir.',
          'Una sola de las seis opciones es falsa.',
          'La evidencia gráfica nunca sobra.'],
  pasos:['Un buen reporte lleva: identificador, título, <b>pasos para reproducir</b>, <b>resultado esperado y real</b>, <b>entorno</b>, <b>severidad</b> y <b>prioridad</b>, evidencia y referencias.',
         'Lo que sobra es el señalamiento personal: el reporte habla del producto, no de quién lo escribió.',
         'La captura de pantalla es evidencia: no sobra, ayuda.'],
  porque:'Nombrar culpables en un reporte es exactamente lo que la psicología de las pruebas del capítulo 1 pide evitar.' },

{ n:44, bloque:5, titulo:'La pirámide', tipo:'opcion',
  enunciado:'Un equipo tiene 4 pruebas unitarias, 30 de integración y 260 de interfaz de usuario. La suite tarda cuatro horas y cada cambio de diseño rompe decenas de pruebas.\n\n¿Qué está pasando y qué dice el modelo?',
  opciones:['Está bien: más pruebas de interfaz significa más cobertura de lo que ve el usuario.',
            'Es una pirámide invertida: la base debería ser de pruebas unitarias, muchas, rápidas y baratas.',
            'Faltan pruebas de aceptación de usuario.',
            'El problema es la herramienta de automatización, no el reparto.'],
  correcta:1,
  pistas:['Dibuja las tres cifras como una figura: ¿qué forma sale?',
          '¿Cuáles son las pruebas lentas y frágiles, y cuáles las rápidas y baratas?',
          'Cuatro horas y roturas constantes son el síntoma clásico.'],
  pasos:['La <b>pirámide de pruebas</b> quiere una base ancha de pruebas unitarias —muchas, rápidas, baratas— y una punta estrecha de pruebas de interfaz —pocas, lentas, frágiles—.',
         'Aquí es al revés: 260 de interfaz sobre 4 unitarias. Es el antipatrón de la <b>pirámide invertida</b> o «cono de helado».',
         'Los síntomas coinciden: suite lenta y roturas masivas ante cualquier cambio de diseño.'],
  porque:'La pirámide se pregunta por la forma y por los síntomas. Cuatro horas de suite es la pista.' },

{ n:45, bloque:5, titulo:'Densidad de defectos', tipo:'numero',
  enunciado:'Dos módulos del mismo sistema:\n\n• Módulo A: 30 defectos encontrados en 6000 líneas de código\n• Módulo B: 12 defectos encontrados en 1000 líneas\n\n¿Cuántos defectos por cada mil líneas tiene el <b>módulo B</b>?',
  respuesta:12,
  pistas:['Densidad de defectos = defectos ÷ (líneas ÷ 1000).',
          'El módulo B tiene exactamente mil líneas.',
          'La cuenta es más simple de lo que parece.'],
  pasos:['Módulo B: 12 defectos en 1000 líneas → <b>12 defectos por cada mil líneas</b>.',
         'Módulo A, para comparar: 30 ÷ 6 = 5 por cada mil líneas.',
         'Aunque A tiene más defectos en total, B está <b>más de dos veces peor</b> por línea.',
         'Eso es agrupación de defectos, medida: B es donde hay que meter más pruebas.'],
  porque:'El número absoluto de defectos engaña. La densidad es lo que señala dónde se están escondiendo.' },

{ n:46, bloque:5, titulo:'Sin gestión de configuración', tipo:'opcion',
  enunciado:'Quien prueba reporta que el defecto DEF-204 ya no aparece. Desarrollo dice que no ha tocado ese módulo. Nadie sabe qué versión del sistema, de los datos ni de los scripts se usó en cada ejecución.\n\n¿Qué falló?',
  opciones:['Falta un criterio de salida bien definido',
            'Falta gestión de la configuración: no se puede saber qué se probó ni reproducirlo',
            'Falta análisis de riesgo',
            'Falta trazabilidad entre requisitos y casos'],
  correcta:1,
  pistas:['El problema no es qué se probó, sino que nadie puede reconstruirlo.',
          'La palabra clave del enunciado es «no sabe qué versión».',
          'Un resultado que no se puede reproducir no sirve como evidencia.'],
  pasos:['La <b>gestión de la configuración</b> garantiza que se sepa exactamente qué versión de qué elemento se probó.',
         'Sin ella, un resultado no es reproducible, y un resultado no reproducible no vale como evidencia.',
         'La <b>trazabilidad</b> es otra cosa: conecta requisitos con casos, no versiones con ejecuciones.'],
  porque:'Es el tema del capítulo 5 que más se subestima, y el que más discusiones estériles evita en la vida real.' },

/* ── BLOQUE 6 · HERRAMIENTAS Y CIERRE ───────────────────────────────────── */
{ n:47, bloque:6, titulo:'Qué automatizar', tipo:'multi',
  enunciado:'Marca los <b>buenos candidatos</b> a automatizar.',
  opciones:['La suite de regresión que se ejecuta en cada versión.',
            'Una prueba exploratoria de una pantalla nueva que cambia cada semana.',
            'Cálculos con muchas combinaciones de datos.',
            'La prueba de humo posterior a cada despliegue.',
            'Una comprobación que se va a ejecutar una sola vez en la vida.',
            'La evaluación de si la interfaz «se siente» cómoda.'],
  correctas:[0,2,3],
  pistas:['Automatizar sale a cuenta cuando algo se repite muchas veces y no cambia todo el tiempo.',
          'Lo que exige criterio humano no se automatiza.',
          'Lo que se ejecuta una sola vez cuesta más automatizarlo que hacerlo a mano.'],
  pasos:['Buenos candidatos: <b>regresión</b>, <b>humo</b>, cálculos con muchos datos, cargas repetitivas.',
         'Malos candidatos: lo que se ejecuta una vez, lo que cambia cada semana, lo exploratorio y todo lo que pide juicio humano.',
         'La automatización no sustituye a las personas: les cambia el trabajo, de repetir a pensar.'],
  porque:'La pregunta se contesta con dos criterios: ¿se repite mucho? y ¿es estable?' },

{ n:48, bloque:6, titulo:'El costo escondido', tipo:'opcion',
  enunciado:'Un equipo automatizó 900 pruebas en seis meses. Un año después la mitad está desactivada, la suite tarda dos horas y nadie confía en los resultados porque «siempre falla algo».\n\n¿Cuál es el riesgo del temario que se materializó?',
  opciones:['Automatizar demasiado rápido al principio',
            'Subestimar el mantenimiento de los scripts y confiar de más en la herramienta',
            'No comprar suficientes licencias',
            'Haber elegido la herramienta equivocada'],
  correcta:1,
  pistas:['El síntoma es que la suite envejeció con el producto y nadie la mantuvo al día.',
          'El segundo síntoma es que dejaron de mirar los resultados.',
          'El temario nombra los dos juntos.'],
  pasos:['La suite envejece con el producto: cada cambio rompe scripts, y mantenerlos cuesta trabajo real que casi nadie presupuesta.',
         'El segundo riesgo es <b>confiar de más</b>: si la herramienta pasa, se asume que todo está bien, y se deja de mirar.',
         'Las otras opciones describen problemas reales pero no son los riesgos que el temario enumera.'],
  porque:'Es la pregunta del capítulo 6 que más cae, porque es la lección que todo el mundo aprende pagando.' },

{ n:49, bloque:6, titulo:'Diseñar la suite completa', tipo:'numero',
  enunciado:'Un formulario de préstamo tiene dos campos:\n\n• <b>Monto</b>: válido de 1000 a 50000. Fuera de rango se rechaza.\n• <b>Plazo</b>: sólo acepta 12, 24 o 36 meses. Cualquier otro valor se rechaza.\n\nSe aplica la regla habitual del diseño de casos: <b>un solo valor inválido por caso</b>, porque si metes dos, el primer rechazo enmascara al segundo y no sabes si el otro se comprobó.\n\n¿Cuántos casos hacen falta como mínimo para el 100 % de cobertura de particiones de los dos campos?',
  respuesta:4,
  pistas:['Cuenta primero las particiones de cada campo por separado.',
          'Monto: una válida y dos inválidas. Plazo: una válida y una inválida.',
          'Con la regla de un solo inválido por caso, cada caso inválido tiene que llevar el otro campo válido.'],
  pasos:['<b>Monto</b>: válida (1000–50000), inválida por abajo, inválida por arriba → <b>3</b> particiones.',
         '<b>Plazo</b>: válida (12, 24 o 36) e inválida (cualquier otro) → <b>2</b> particiones.',
         'Caso 1 — monto válido + plazo válido: cubre las dos particiones válidas.',
         'Caso 2 — monto por debajo de 1000 + plazo válido.',
         'Caso 3 — monto por encima de 50000 + plazo válido.',
         'Caso 4 — monto válido + plazo inválido.',
         'Las 3 particiones de monto y las 2 de plazo quedan cubiertas con <b>4 casos</b>. Sin la regla del inválido único podrías intentarlo con 3, pero el rechazo temprano dejaría una partición sin comprobar de verdad.'],
  porque:'Es el ejercicio que junta todo: contar particiones, combinar campos y entender por qué no se meten dos valores inválidos en el mismo caso.' },

{ n:50, bloque:6, titulo:'El último: encontrar el defecto', tipo:'linea',
  enunciado:'La regla completa del cobro de envío:\n\n• hasta 5 kg inclusive → 50 pesos fijos\n• más de 5 y hasta 20 kg → 10 pesos por kilo\n• más de 20 kg → se rechaza\n\nLa prueba con <b>peso = 5</b> devuelve 50 pesos: bien. La prueba con <b>peso = 20</b> devuelve «rechazado»: mal, debería cobrar 200.\n\n¿En qué línea está el defecto?',
  codigo:['leer peso','si peso <= 5 entonces','· costo = 50','si no si peso < 20 entonces','· costo = peso * 10','si no','· costo = "rechazado"','fin si','imprimir costo'],
  respuesta:4,
  pistas:['Recorre el código con peso = 20 y anota qué rama toma.',
          'La regla dice «hasta 20 inclusive». El código dice otra cosa.',
          'Compara el operador de la línea 4 con las palabras de la especificación.'],
  pasos:['Con peso = 20: la línea 2 (20 &lt;= 5) es falsa.',
         'La línea 4 evalúa <b>20 &lt; 20</b>, que es <b>falso</b>, así que cae en el «si no» y devuelve «rechazado».',
         'La especificación dice «hasta 20 <b>inclusive</b>»: el operador correcto es <b>&lt;=</b>.',
         'El defecto está en la <b>línea 4</b>.',
         'Fíjate en que la línea 2 sí está bien (&lt;= 5 para «hasta 5 inclusive»): el defecto es sólo el segundo límite, y por eso la primera prueba pasaba.'],
  porque:'Éste es el examen completo en un ejercicio: leer la especificación palabra por palabra, aplicar valores límite y localizar la línea. Un caso pasaba y el otro no, que es como se ven los defectos de límite en la vida real.' },
