/* ── BLOQUE 3 · PRUEBAS ESTÁTICAS ───────────────────────────────────────── */
{ n:16, bloque:3, titulo:'Sin ejecutar nada', tipo:'multi',
  enunciado:'Marca las que son <b>pruebas estáticas</b>.',
  opciones:['Una inspección del documento de requisitos.',
            'Ejecutar la prueba de humo después del despliegue.',
            'Pasar una herramienta de análisis de código que marca variables sin usar.',
            'Una revisión técnica del diseño de arquitectura.',
            'Revisar entre dos personas los casos de prueba antes de ejecutarlos.'],
  correctas:[0,2,3,4],
  pistas:['Estática significa una sola cosa: sin ejecutar el software.',
          'Sólo una de las cinco ejecuta algo.',
          'Los casos de prueba también son un producto de trabajo revisable.'],
  pasos:['Estática = examinar sin ejecutar. Dinámica = ejecutar.',
         'La prueba de humo se ejecuta: es la única dinámica de la lista.',
         'El análisis de código con herramienta es estático aunque lo haga una máquina.',
         'Revisar los casos de prueba también es estática: cualquier producto de trabajo legible se puede revisar.'],
  porque:'La pregunta es fácil y se falla por leer de prisa. Lo que se revisa puede ser cualquier cosa, no sólo código.' },

{ n:17, bloque:3, titulo:'Qué revisión es', tipo:'opcion',
  enunciado:'Reunión con roles definidos y un moderador formado que la conduce. Hay criterios de entrada y de salida, se recogen métricas de defectos encontrados por hora y el autor <b>no</b> dirige la sesión.\n\n¿Qué tipo de revisión es?',
  opciones:['Revisión informal','Walkthrough (revisión guiada)','Revisión técnica','Inspección'],
  correcta:3,
  pistas:['Ordena de menos a más formal: informal, walkthrough, técnica, inspección.',
          'Las métricas y los criterios de entrada y salida sólo aparecen en la más formal.',
          'Que el autor no dirija es una pista fuerte: en el walkthrough sí dirige.'],
  pasos:['La <b>inspección</b> es la más formal: moderador, roles definidos, métricas, criterios de entrada y salida.',
         'El <b>walkthrough</b> lo conduce el autor y sirve para evaluar, formar y consensuar.',
         'La <b>revisión técnica</b> la hacen pares técnicos, con documentación, pero sin toda la maquinaria de la inspección.',
         'La <b>informal</b> no tiene proceso ni deja documentación obligatoria.'],
  porque:'La oposición que más cae es «en el walkthrough dirige el autor, en la inspección no».' },

{ n:18, bloque:3, titulo:'El orden de una revisión formal', tipo:'opcion',
  enunciado:'Ordena las etapas de una revisión formal según el temario.',
  opciones:['Inicio → planificación → revisión individual → corrección → comunicación',
            'Planificación → revisión individual → inicio → corrección → comunicación',
            'Planificación → inicio → revisión individual → comunicación y análisis → corrección y reporte',
            'Revisión individual → planificación → inicio → comunicación → corrección'],
  correcta:2,
  pistas:['La planificación siempre va primero: decide qué se revisa y con quién.',
          'La revisión individual va DESPUÉS del inicio (donde se reparte el material) y ANTES de la reunión.',
          'La corrección es lo último, no lo penúltimo.'],
  pasos:['1 · <b>Planificación</b>: alcance, personas, criterios de entrada y salida.',
         '2 · <b>Inicio</b>: se reparte el material y se explica el objetivo.',
         '3 · <b>Revisión individual</b>: cada quien revisa por su cuenta y anota hallazgos.',
         '4 · <b>Comunicación y análisis</b>: la reunión, donde se juntan y clasifican los hallazgos.',
         '5 · <b>Corrección y reporte</b>: el autor corrige y se cierra.'],
  porque:'La señal para descartar opciones: la revisión individual va entre el inicio y la reunión. Si una opción la pone en otro sitio, se cae.' },

{ n:19, bloque:3, titulo:'Lo que una herramienta sí puede ver', tipo:'multi',
  enunciado:'Marca lo que un <b>analizador estático de código</b> puede detectar por sí solo.',
  opciones:['Una variable declarada y nunca usada.',
            'Que el cálculo del IVA da 15 % en vez de 16 %.',
            'Código inalcanzable después de un return.',
            'Que la interfaz le resulta confusa a la persona usuaria.',
            'Un incumplimiento del estándar de codificación de la casa.',
            'Complejidad ciclomática por encima del umbral.'],
  correctas:[0,2,4,5],
  pistas:['La herramienta lee la estructura, no entiende el negocio.',
          'Nada que dependa de saber qué DEBERÍA hacer el sistema está a su alcance.',
          'Dos de las seis requieren una persona.'],
  pasos:['El análisis estático ve la <b>estructura</b>: variables sin usar, código muerto, complejidad, estándares, tipos.',
         'No ve la <b>corrección de la lógica de negocio</b>: no sabe que el IVA es 16 %.',
         'Y no ve nada de experiencia de uso: para eso hace falta una persona.'],
  porque:'Es el límite que hay que tener claro para no confiar de más en las herramientas ni de menos.' },

{ n:20, bloque:3, titulo:'Los dos que se confunden', tipo:'opcion',
  enunciado:'¿Cuál es la diferencia entre el <b>líder de revisión</b> y el <b>moderador</b>?',
  opciones:['Son sinónimos; cambia el nombre según el país.',
            'El líder decide qué se revisa y organiza; el moderador conduce la reunión y media.',
            'El moderador escribe el producto de trabajo; el líder lo revisa.',
            'El líder sólo aparece en revisiones informales.'],
  correcta:1,
  pistas:['Uno decide y organiza antes. El otro conduce durante.',
          'En equipos pequeños los junta la misma persona, pero el temario los distingue.',
          'Ninguno de los dos escribe el producto de trabajo: ése es el autor.'],
  pasos:['<b>Líder de revisión</b>: decide el alcance, las personas y el momento. Trabaja antes.',
         '<b>Moderador</b>: conduce la sesión, cuida el tono, media si hay fricción. Trabaja durante.',
         'Los otros roles son <b>autor</b> (escribió el producto), <b>escriba</b> (registra hallazgos), <b>revisores</b> y <b>gerencia</b>.'],
  porque:'En la vida real los junta la misma persona y por eso se olvida que son dos roles. En el examen se preguntan separados.' },
