/* ── BLOQUE 1 · FUNDAMENTOS ─────────────────────────────────────────────── */
{ n:1, bloque:1, titulo:'La cadena de tres', tipo:'opcion',
  enunciado:'Una programadora escribe <b>&gt;</b> donde iba <b>&gt;=</b>. El sistema acepta pedidos de cero piezas. Tres semanas después el almacén se queda sin inventario registrado y un cliente reclama.\n\n¿Cuál de estas listas nombra las tres cosas <b>en orden</b>?',
  opciones:['Error → defecto → fallo','Defecto → error → fallo','Fallo → defecto → causa raíz','Error → fallo → defecto'],
  correcta:0,
  pistas:['Empieza por la persona: ¿qué hizo un ser humano?',
          'Lo que quedó escrito en el código no se llama igual que la equivocación de la persona.',
          'El almacén vacío es lo último de los tres, y sólo aparece al ejecutar.'],
  pasos:['La persona se equivocó al teclear. Eso es el <b>error</b> (en inglés, <i>error</i> o <i>mistake</i>).',
         'Esa equivocación dejó algo mal dentro del código: el <b>&gt;</b> que debía ser <b>&gt;=</b>. Eso es el <b>defecto</b>.',
         'Al ejecutarse, el sistema se comporta mal y alguien lo ve. Eso es el <b>fallo</b>.',
         'La razón de fondo —prisa, especificación ambigua, falta de revisión— sería la <b>causa raíz</b>, que es una cuarta cosa y no entra en la cadena de tres.'],
  porque:'Si te aprendes la cadena en ese orden, tres o cuatro preguntas del examen real se contestan solas. Es el concepto más preguntado del capítulo 1.' },

{ n:2, bloque:1, titulo:'El fallo sin defecto', tipo:'multi',
  enunciado:'Marca <b>todas</b> las afirmaciones que sean ciertas según el temario.',
  opciones:['Todo fallo tiene forzosamente un defecto detrás.',
            'Un fallo puede deberse a condiciones ambientales: radiación, campos magnéticos, contaminación.',
            'Un defecto puede estar años en el código sin provocar ningún fallo.',
            'Encontrar un defecto en una revisión, sin ejecutar nada, es imposible.'],
  correctas:[1,2],
  pistas:['Dos son falsas y las dos suenan a regla de oro. Desconfía justo de ésas.',
          'El temario menciona expresamente unas causas físicas de fallo.',
          'Piensa en un defecto en una rama de código que nadie ejecuta nunca.'],
  pasos:['La primera es falsa: el temario reconoce fallos por condiciones ambientales, sin defecto en el software.',
         'La segunda es la excepción exacta que menciona el temario.',
         'La tercera es cierta y es la base de la agrupación de defectos: un defecto existe aunque nadie lo ejecute.',
         'La cuarta es falsa: eso es precisamente la prueba estática, que encuentra defectos <b>sin</b> ejecutar.'],
  porque:'Las dos falsas son las trampas típicas: absolutos que suenan bien. En el examen, un «todo» o un «nunca» merece una segunda lectura.' },

{ n:3, bloque:1, titulo:'Dónde cae cada actividad', tipo:'opcion',
  enunciado:'El equipo está evaluando el documento de requisitos para escribir la lista de lo que hay que probar. Todavía no hay ni un caso de prueba escrito.\n\n¿En qué actividad del proceso de prueba están?',
  opciones:['Planificación','Análisis','Diseño','Implementación'],
  correcta:1,
  pistas:['Ordena mentalmente: planificar, analizar, diseñar, implementar, ejecutar, completar.',
          'La pregunta clave es: ¿estamos decidiendo QUÉ probar o CÓMO probarlo?',
          'Todavía no hay casos, sólo condiciones.'],
  pasos:['El <b>análisis</b> contesta <b>qué</b> probar: identifica las condiciones de prueba a partir de la base de prueba.',
         'El <b>diseño</b> contesta <b>cómo</b>: convierte esas condiciones en casos concretos con entradas y resultados esperados.',
         'La <b>implementación</b> es la carpintería: procedimientos, datos, entorno.',
         'La <b>planificación</b> ocurre antes de todo y define alcance, riesgos y criterios.'],
  porque:'Análisis y diseño se confunden constantemente. El truco: análisis = condiciones, diseño = casos.' },

{ n:4, bloque:1, titulo:'Qué principio explica esto', tipo:'opcion',
  enunciado:'Un equipo lleva catorce meses ejecutando la misma suite de 340 pruebas automatizadas en cada versión. Los últimos siete meses no ha encontrado un solo defecto nuevo. En producción, mientras tanto, siguen apareciendo.\n\n¿Qué principio de las pruebas explica lo que pasa?',
  opciones:['Las pruebas exhaustivas son imposibles','Los defectos se agrupan','La paradoja del pesticida','La ausencia de defectos es una falacia'],
  correcta:2,
  pistas:['El dato clave no es que no encuentren nada: es que llevan catorce meses con LAS MISMAS pruebas.',
          'Piensa en un insecticida que se usa siempre igual.',
          'La solución no es ejecutarlas más veces.'],
  pasos:['Los mismos casos dejan de encontrar defectos porque ya mataron los que sabían matar. Eso es la <b>paradoja del pesticida</b>.',
         'La solución es revisar y <b>ampliar</b> los casos, no repetirlos con más frecuencia.',
         'No es agrupación de defectos: ésa dice que los defectos se concentran en pocos módulos.',
         'No es la falacia de ausencia de defectos: ésa habla de un producto sin defectos que aun así no sirve.'],
  porque:'Es el principio que justifica el mantenimiento de la suite. En el examen se reconoce por «las mismas pruebas» + «ya no encuentran nada».' },

{ n:5, bloque:1, titulo:'Verificar o validar', tipo:'multi',
  enunciado:'Marca las actividades que son de <b>validación</b> (no de verificación).',
  opciones:['Comprobar que el cálculo del IVA coincide con lo que dice la especificación.',
            'Sentar a tres personas usuarias reales a completar una compra y ver si lo logran.',
            'Revisar que el diseño de la base de datos cumple el modelo aprobado.',
            'Preguntarle al dueño del negocio si el reporte que sale le sirve para decidir.'],
  correctas:[1,3],
  pistas:['Verificar mira hacia el documento. Validar mira hacia la persona.',
          '«¿Lo construimos bien?» contra «¿construimos lo correcto?».',
          'Dos de las cuatro comparan contra una especificación escrita.'],
  pasos:['<b>Verificación</b>: ¿lo construimos conforme a lo especificado? Se compara contra un documento.',
         '<b>Validación</b>: ¿esto le sirve a quien lo va a usar? Se compara contra la necesidad real.',
         'La 1 y la 3 comparan contra especificación y modelo: verificación.',
         'La 2 y la 4 preguntan si sirve de verdad: validación.',
         'Ojo: las dos pueden ser estáticas o dinámicas. No es «verificar = estático».'],
  porque:'La opción tramposa del examen suele ser «verificar es estático y validar es dinámico». Es falsa.' },

{ n:6, bloque:1, titulo:'El objetivo cambia con el nivel', tipo:'opcion',
  enunciado:'¿Cuál de estos objetivos es propio de las <b>pruebas de aceptación</b> y no de las de componente?',
  opciones:['Encontrar el mayor número de defectos posible','Medir la cobertura de sentencias',
            'Generar confianza en que el producto sirve para lo que se necesita',
            'Verificar que cada función interna devuelve lo esperado'],
  correcta:2,
  pistas:['¿Quién ejecuta las pruebas de aceptación y qué decisión toma después?',
          'Dos opciones hablan de código interno. Ésas son de componente.',
          'La aceptación produce una decisión de negocio, no una métrica técnica.'],
  pasos:['En componente el objetivo es encontrar defectos y medir cobertura estructural.',
         'En aceptación el objetivo es <b>generar confianza</b> y dar evidencia para decidir si se acepta el producto.',
         'La cobertura de sentencias es una métrica de caja blanca: no se pide en aceptación.'],
  porque:'El temario insiste en que los objetivos dependen del nivel y del momento. Es el sustento de media docena de preguntas.' },

{ n:7, bloque:1, titulo:'Probar no es depurar', tipo:'multi',
  enunciado:'Marca las que son actividades de <b>prueba</b>. Las demás son depuración.',
  opciones:['Ejecutar un caso y registrar que el resultado no coincide con el esperado.',
            'Poner puntos de interrupción y recorrer el código hasta encontrar la línea culpable.',
            'Escribir el reporte de defecto con los pasos para reproducirlo.',
            'Corregir la condición y volver a compilar.',
            'Volver a ejecutar el caso que fallaba para comprobar que ya pasa.'],
  correctas:[0,2,4],
  pistas:['La frontera está en el verbo: si estás cambiando código, ya no estás probando.',
          'Reportar es prueba. Localizar y corregir es depuración.',
          'La última es una prueba de confirmación, y las pruebas de confirmación son prueba.'],
  pasos:['Probar = ejecutar, comparar, registrar y reportar.',
         'Depurar = localizar la causa en el código y corregirla. La hace quien desarrolla.',
         'Volver a ejecutar el caso tras la corrección es <b>prueba de confirmación</b>: prueba, no depuración.'],
  porque:'El examen pregunta esta frontera de varias formas. Quien depura no está probando, aunque sea la misma persona.' },

{ n:8, bloque:1, titulo:'El agujero de la trazabilidad', tipo:'numero',
  enunciado:'Una matriz de trazabilidad tiene cinco requisitos. Los casos de prueba cubren así:\n\n• R1 → CP-01, CP-02\n• R2 → CP-03\n• R3 → (ninguno)\n• R4 → CP-04, CP-05, CP-06\n• R5 → (ninguno)\n\n¿Cuál es el <b>porcentaje de cobertura de requisitos</b>? Escribe sólo el número.',
  respuesta:60, unidad:'%',
  pistas:['La cobertura de requisitos no cuenta casos: cuenta requisitos.',
          'Un requisito está cubierto si tiene AL MENOS un caso. Tener tres no cuenta más que tener uno.',
          'Cuenta cuántos de los cinco tienen al menos un caso.'],
  pasos:['Requisitos con al menos un caso: R1, R2 y R4. Son <b>3</b>.',
         'Requisitos totales: <b>5</b>.',
         '3 ÷ 5 = 0,6 → <b>60 %</b>.',
         'El error frecuente es contar los seis casos de prueba y dividir por algo. La cobertura de requisitos se mide en requisitos.'],
  porque:'Es exactamente para esto que sirve la trazabilidad: R3 y R5 no los prueba nadie, y sin la matriz nadie se entera.' },
