/* ── BLOQUE 2 · PRUEBAS A LO LARGO DEL CICLO DE VIDA ────────────────────── */
{ n:9, bloque:2, titulo:'Cada prueba en su nivel', tipo:'opcion',
  enunciado:'Tu sistema de facturación manda los datos del comprobante a un <b>servicio externo del SAT</b> y espera un folio de vuelta. Estás comprobando que el intercambio funciona y que los campos llegan como el otro sistema los espera.\n\n¿En qué nivel de prueba estás?',
  opciones:['Prueba de componente','Prueba de integración de componentes','Prueba de integración de sistemas','Prueba de aceptación de usuario'],
  correcta:2,
  pistas:['La palabra que decide está en negritas en el enunciado.',
          '¿El otro extremo es un módulo tuyo o un sistema de alguien más?',
          'Integración de componentes y de sistemas se distinguen por dónde está la frontera.'],
  pasos:['<b>Integración de componentes</b>: interfaces entre módulos <b>del mismo sistema</b>.',
         '<b>Integración de sistemas</b>: interfaces con <b>otros sistemas</b> o servicios externos.',
         'El SAT es otro sistema, así que es integración de sistemas.',
         'No es aceptación: no estás decidiendo si el negocio acepta el producto, estás comprobando un intercambio técnico.'],
  porque:'Es de las preguntas que más caen, y siempre se juega con la misma distinción: dentro del sistema o fuera de él.' },

{ n:10, bloque:2, titulo:'Alfa, beta y quién está dónde', tipo:'opcion',
  enunciado:'La empresa invita a doce clientes a sus oficinas, les presta computadoras y les pide que usen la nueva versión durante una tarde, con gente de desarrollo a un lado tomando notas.\n\n¿Qué prueba es?',
  opciones:['Prueba beta, porque la hacen clientes','Prueba alfa, porque se hace en las instalaciones de quien desarrolla',
            'Prueba de aceptación operativa','Prueba de humo'],
  correcta:1,
  pistas:['Lo que separa alfa de beta no es quién la hace.',
          'Es el sitio.',
          'Los clientes están en las oficinas de la empresa que desarrolla.'],
  pasos:['<b>Alfa</b>: en las instalaciones de quien desarrolla, aunque la ejecuten personas usuarias invitadas.',
         '<b>Beta</b>: en el entorno real de quien usa, en su propia casa u oficina.',
         'Aquí los clientes están en las oficinas de la empresa: es alfa.',
         'La trampa está en «la hacen clientes»: eso no basta para que sea beta.'],
  porque:'La definición se recuerda mal en la mitad de los cursos. El criterio es el LUGAR, no la persona.' },

{ n:11, bloque:2, titulo:'Confirmación y regresión', tipo:'multi',
  enunciado:'Se corrigió el defecto DEF-118 en el módulo de descuentos. Marca <b>todo lo que corresponde hacer</b> y clasifícalo bien: marca sólo las afirmaciones <b>correctas</b>.',
  opciones:['Volver a ejecutar el caso que detectó DEF-118 es una prueba de confirmación.',
            'Ejecutar la suite del módulo de carrito, que usa descuentos, es una prueba de regresión.',
            'La prueba de regresión sirve para comprobar que la corrección funcionó.',
            'Si el módulo de descuentos lo usan cinco módulos más, el análisis de impacto dice cuánta regresión hace falta.'],
  correctas:[0,1,3],
  pistas:['Confirmación = «¿ya quedó?». Regresión = «¿rompí algo más?».',
          'Una de las cuatro intercambia las dos definiciones.',
          'El análisis de impacto es lo que dimensiona el alcance de la regresión.'],
  pasos:['Confirmación: volver a ejecutar el caso que falló, para ver si la corrección sirvió. Afirmación 1: correcta.',
         'Regresión: ejecutar otras pruebas para ver si el cambio rompió algo que funcionaba. Afirmación 2: correcta.',
         'Afirmación 3 es <b>falsa</b>: eso es confirmación, no regresión.',
         'Afirmación 4: correcta. Sin análisis de impacto sólo quedan dos opciones malas: probar todo o probar a ciegas.'],
  porque:'En la práctica se hacen juntas, y por eso se confunden. En el examen se preguntan por separado.' },

{ n:12, bloque:2, titulo:'Funcional o no funcional', tipo:'multi',
  enunciado:'Marca las comprobaciones <b>no funcionales</b>.',
  opciones:['Que el sistema responda en menos de 2 segundos con 500 usuarios simultáneos.',
            'Que el descuento de socio se aplique sólo si el monto supera 1000 pesos.',
            'Que una persona nueva complete el alta sin ayuda en menos de tres minutos.',
            'Que la app funcione igual en Android 12 y en Android 15.',
            'Que el botón «guardar» guarde.'],
  correctas:[0,2,3],
  pistas:['Funcional es QUÉ hace. No funcional es CÓMO DE BIEN lo hace.',
          'Rendimiento, usabilidad, compatibilidad, seguridad, portabilidad y fiabilidad son no funcionales.',
          'Dos de las cinco describen una regla de negocio.'],
  pasos:['1 es rendimiento → no funcional.',
         '2 es una regla de negocio → funcional.',
         '3 es usabilidad → no funcional.',
         '4 es compatibilidad → no funcional.',
         '5 es comportamiento esperado → funcional.'],
  porque:'La pregunta se contesta en dos segundos si tienes la lista de características no funcionales en la cabeza.' },

{ n:13, bloque:2, titulo:'Shift left, en un caso real', tipo:'opcion',
  enunciado:'Un requisito decía «el sistema notificará al usuario oportunamente». Nadie preguntó qué significa «oportunamente». Se implementó como 24 horas; el cliente esperaba 5 minutos. Se descubrió en la prueba de aceptación, a tres días de salir, y costó rehacer el módulo de notificaciones.\n\n¿Qué actividad, aplicando <i>shift left</i>, lo habría evitado más barato?',
  opciones:['Automatizar las pruebas de aceptación desde el primer sprint',
            'Revisar el documento de requisitos y marcar «oportunamente» como ambiguo',
            'Aumentar la cobertura de ramas del módulo de notificaciones',
            'Ejecutar pruebas de rendimiento antes de la aceptación'],
  correcta:1,
  pistas:['El defecto no está en el código: está en el requisito.',
          'Shift left significa llevar la actividad de prueba lo más temprano posible.',
          'La actividad más temprana posible aquí no ejecuta nada.'],
  pasos:['El defecto se introdujo en el requisito, con una palabra ambigua.',
         'La actividad de prueba más temprana que existe es la <b>prueba estática</b>: revisar el documento.',
         'Una revisión habría marcado «oportunamente» como no comprobable y habría costado minutos.',
         'Las otras tres opciones actúan sobre el código, es decir, después de que el defecto ya existe.'],
  porque:'Es el argumento económico del temario: un defecto de requisitos corregido en revisión cuesta minutos; descubierto en aceptación, una versión de emergencia.' },

{ n:14, bloque:2, titulo:'Qué dispara el mantenimiento', tipo:'multi',
  enunciado:'Marca los <b>desencadenantes de pruebas de mantenimiento</b>.',
  opciones:['La primera versión del producto sale a producción.',
            'Se migra la base de datos a otro motor.',
            'Se actualiza el sistema operativo de los servidores.',
            'Se retira del aire un módulo y hay que archivar sus datos.',
            'Se está diseñando la arquitectura de un producto nuevo.'],
  correctas:[1,2,3],
  pistas:['Mantenimiento es lo que pasa DESPUÉS de que el producto ya está en operación.',
          'Modificación, migración y retiro son las tres familias.',
          'Dos de las cinco ocurren antes de que el producto exista en operación.'],
  pasos:['Los desencadenantes son <b>modificaciones</b> (correcciones, mejoras), <b>migraciones</b> (de plataforma, de datos) y el <b>retiro</b> del sistema.',
         'La primera versión es desarrollo, no mantenimiento.',
         'Diseñar la arquitectura es todavía más temprano.'],
  porque:'El retiro sorprende a mucha gente: archivar y migrar datos al apagar un sistema también se prueba.' },

{ n:15, bloque:2, titulo:'Cuánta regresión hace falta', tipo:'numero',
  enunciado:'Se cambia el módulo <b>M3</b>. El mapa de dependencias dice quién llama a quién:\n\n• M1 → llama a M3\n• M2 → llama a M1\n• M4 → llama a M3\n• M5 → no llama a nadie\n• M6 → llama a M4\n\nSin contar M3, ¿cuántos módulos hay que meter en la regresión porque dependen de él <b>directa o indirectamente</b>?',
  respuesta:4,
  pistas:['No basta con mirar quién llama a M3: también hay que subir un nivel más.',
          'Si M2 llama a M1 y M1 llama a M3, un cambio en M3 puede llegar hasta M2.',
          'M5 no llama a nadie: queda fuera.'],
  pasos:['Directos sobre M3: <b>M1</b> y <b>M4</b>.',
         'Quien depende de M1: <b>M2</b>. Quien depende de M4: <b>M6</b>.',
         'M5 no depende de nada, queda fuera.',
         'Total: M1, M2, M4 y M6 = <b>4 módulos</b>.'],
  porque:'Esto es el análisis de impacto hecho a mano. El error típico es quedarse en los llamadores directos y perder la cadena.' },
